spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true #当多个bean遇到同样名字的时候，是否允许覆盖注册
server:
  port: 8102
  tomcat:
    uri-encoding: UTF-8
    max-connections: 2000
    max-threads: 1000
    min-spare-threads: 64
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/ #注册中心地址
zuul:
#  ignoredPatterns: '*'
  routes:
    all-service:
      path: /api/all/**
      serviceId: all-service