spring:
  main:
    allow-bean-definition-overriding: true #当多个bean遇到同样名字的时候，是否允许覆盖注册
  dataSource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/xu?useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#  内存设置用户名、密码、角色
#  security:
#    user:
#      name: root
#      password: root
#      roles: admin, user
server:
  port: 8102
  tomcat:
    uri-encoding: UTF-8
    max-connections: 2000
    max-threads: 1000
    min-spare-threads: 64
zuul:
  sensitiveHeaders:
  routes:
    all-service:
      path: /api/all/**
      serviceId: all
      stripPrefix: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
feign:
  hystrix:
    enabled: true